Synchronized the proteome scanning code with the new interface

diff --git a/proteome-scan b/proteome-scan
--- a/proteome-scan
+++ b/proteome-scan
@@ -6,41 +6,58 @@ KMERS_GET="${PSCAN_DIR}/tools/kmers-get"
 KMERS2PRED="${PSCAN_DIR}/tools/kmers2pred"
 PROB_MAPPER="${PSCAN_DIR}/tools/prob-map"
 EPITOPES_EX="${PSCAN_DIR}/tools/epitopes-extract"
+EPIRANKER="${PSCAN_DIR}/tools/epiranker"
 
 print_usage() {
     local script_name=$(basename "${BASH_SOURCE[0]}")
-    echo "Usage: $script_name <fasta-file> <allele-list> <output-director>"
+    echo "Usage: $script_name -l <allele-list> -o <output-directory> <fasta-file>" >&2
 }
 err_echo() {
     local script_name=$(basename "${BASH_SOURCE[0]}")
     echo "$script_name" "$1" >&2
 }
 
-if [ ! -f "$KMERS_GET" ] || [ ! -f "$KMERS2PRED" ] || [ ! -f "$PROB_MAPPER" ]; then
+if [ ! -f "$KMERS_GET" ] || [ ! -f "$KMERS2PRED" ] || [ ! -f "$PROB_MAPPER" ] || \
+   [ ! -f "$EPITOPES_EX" ] || [ ! -f "$EPIRANKER" ]; then
     err_echo "Some of the scripts required for running the Proteome scan are missing"
     print_usage
     exit 1
 fi
 
+# Defaults
+odir="proteome-scanning"
+acutoff=0.2
+bcutoff=0.5
 
+while getopts "a:b:l:o:" option; do
+    case $option in
+        a) 
+            acutoff="$OPTARG" ;;
+        b) 
+            bcutoff="$OPTARG" ;;
+        l)
+            al_lst="$OPTARG" ;;
+        o)
+            odir="$OPTARG"   ;;
+        \?)
+            echo "Error: Illegal option"
+            exit 1;;
+    esac
+done
+
+shift $((OPTIND-1))
 fasta_f="$1"
-al_lst="$2"
+
 if [ -z "$fasta_f" ] || [ -z "$al_lst" ] || [ ! -e "$fasta_f" ] || [ ! -e "$al_lst" ]; then
     err_echo "One or more of the file inputs are missing"
     print_usage
     exit 2
 fi
 
-odir="$3"
-if [ -z "$odir" ]; then
-    odir='proteome-scan'
-else
-    odir="$3"
-fi
-
 "$KMERS_GET" "$fasta_f" "$odir"
 if [ $? -ne 0 ]; then
     err_echo "Something went wrong when generating kmers from the input FASTA file"
+    print_usage
     exit 3
 fi
 
@@ -61,7 +78,11 @@ for allele in $(cat "$al_lst"); do
     if [ $? -ne 0 ]; then
         exit 5
     fi
-    
-    scan_f="${odir}/prot-scan/${allele_str}.scan.gz"
-    "$EPITOPES_EX" "$fasta_f" "$scan_f" 0.5 "${odir}/epitopes" "${allele_str}"
+
+    # If no cutoff value is given, then don't extract the eptiopes
+    if [ ! -z "$acutoff" ] || [ ! -z "$bcutoff" ]; then
+        echo "Extracting eptiopes at cutoffs: ($acutoff, $bcutoff)"
+        scan_f="${odir}/prot-scan/${allele_str}.scan.gz"
+        "$EPITOPES_EX" -a "$acutoff" -b "$bcutoff" -f "${allele_str}" -o "${odir}/epitopes" "$fasta_f" "$scan_f"
+    fi
 done
diff --git a/tools/epitopes-extract b/tools/epitopes-extract
--- a/tools/epitopes-extract
+++ b/tools/epitopes-extract
@@ -33,6 +33,32 @@ writefn() {
 #------------------------------------------------#
 #                Input validation                #
 #------------------------------------------------#
+
+odir="proteome-scanning"
+acutoff=0.2
+bcutoff=0.5
+fbase="epitopes"
+
+while getopts "a:b:f:l:o:" option; do
+    case $option in
+        a)
+            acutoff="$OPTARG" ;;
+        b)
+            bcutoff="$OPTARG" ;;
+        f)
+            fbase="$OPTARG" ;;
+        l)
+            al_lst="$OPTARG" ;;
+        o)
+            odir="$OPTARG"   ;;
+        \?)
+            echo "Error: Illegal option"
+            exit 1;;
+    esac
+done
+
+shift $((OPTIND-1))
+
 fasta_f="$1"
 scan_f="$2"
 
@@ -50,28 +76,21 @@ if [ ! -e "$fasta_f" ] || [ ! -e "$scan_f" ]; then
     exit 2
 fi
 
-if [ -z "$3" ]; then
-    cutoff=0.5
-else
-    cutoff="$3"
-fi
-
 float_pat='^[0-9]+[.]*[0-9]*$'
-if ! [[ "$cutoff" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]; then
-    err_echo "The input cutoff is not a valid floating point number"
+if ! [[ "$acutoff" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]; then
+    err_echo "The input acutoff is not a valid floating point number"
     exit 3
 fi
 
-# Ready the output directory
-if [ ! -z "$4" ]; then
-    odir="$4"
-    [ ! -d "$odir" ] && mkdir -p "$odir"
-    if [ -z "$5" ]; then
-        fbase="epitopes"
-    else
-        fbase="$5"
-    fi
+if ! [[ "$bcutoff" =~ ^[+-]?[0-9]+\.?[0-9]*$ ]]; then
+    err_echo "The input bcutoff is not a valid floating point number"
+    exit 3
 fi
+
+
+# Ready the output directory
+odir="${odir}/aff${acutoff}_bind${bcutoff}"
+[ ! -d "$odir" ] && mkdir -p "$odir"
 
 # Check [4]: Ensure that gawk is available somewhere
 gawk_chk=$(command -v gawk)
@@ -85,7 +104,7 @@ chksum_compute() {
 }
 
 if [ ! -z "$odir" ]; then
-    outf="${odir}/${fbase}.fa.gz"
+    outf="${odir}/${fbase}.tsv.gz"
     outf_lock="${odir}/${fbase}.scan.md5"
     write_flag=1
 else
@@ -119,7 +138,7 @@ fi
 # This is justified by the expectation that some
 # proteome scanning might be carried out only
 # for subsets of proteins.
-gawk -F'\t' -vK=9 -vfasta_f=<(readfn "${fasta_f}") -vcutoff="$cutoff" '
+gawk -F'\t' -vK=9 -vfasta_f=<(readfn "${fasta_f}") -vacutoff="$acutoff" -vbcutoff="$bcutoff" '
 
 function trimws(s) {
     sub(/^[[:space:]]+/, "", s)
@@ -150,6 +169,7 @@ BEGIN {
     curr_hd  = ""
     curr_seq = ""
     if (K == "") { K = 9 }
+    print "protein\tlen\tepitope_startpos\tepitope\tbindprob\tbindaff\trank\trankp"
 }
 
 NR > 1 {
@@ -158,17 +178,31 @@ NR > 1 {
         print "The ID: ["prot_id"] is not present in the FASTA file"
         exit 1
     }
+
+    # This is for binding probability
     split($2, window_arr, ",")
-    exp_wlen = len_arr[prot_id] - K + 1
+    plen = len_arr[prot_id]
+    exp_wlen = plen - K + 1
     if (exp_wlen != length(window_arr)) {
         print "There is a length mismatch between the FASTA file and the proteome scanning input for ["prot_id"]"
         exit 2
     }
 
-    print ">"prot_id
+    # This is for binding affinity
+    split($3, aff_arr, ",")
+
+    # This is for intra-protein epitope rank
+    split($6, rank_arr, ",")
+    nranks = length(rank_arr)
+
     for (i = 1; i <= exp_wlen; i++) {
-        v = window_arr[i]
-        if (v > cutoff) { print substr(seq_arr[prot_id], i, K) }
+        b = window_arr[i]
+        a = aff_arr[i]
+        if ((a >= acutoff) && (b >= bcutoff)) {
+            r = rank_arr[i]
+            rp = sprintf("%0.2f", rank_arr[i] * 100 / nranks)
+            print prot_id"\t"plen"\t"i"\t"substr(seq_arr[prot_id], i, K)"\t"b"\t"a"\t"r"\t"rp
+        }
     }
 }
 ' <(readfn "$scan_f") | writefn "$write_flag" > "$outf"
